bundles = {}

[versions]
	spring-boot = "3.3.5"

	[plugins.spring-boot]
		id = "org.springframework.boot"

		[plugins.spring-boot.version]
			ref = "spring-boot"

	[libraries.spring-boot-starter]
		name = "spring-boot-starter"
		group = "org.springframework.boot"

	[libraries.spring-boot-starter-test]
		name = "spring-boot-starter-test"
		group = "org.springframework.boot"

	[libraries.spring-boot-dependencies]
		name = "spring-boot-dependencies"
		group = "org.springframework.boot"

		[libraries.spring-boot-dependencies.version]
			ref = "spring-boot"

	[libraries.spring-boot-configuration-processor]
		name = "spring-boot-configuration-processor"
		group = "org.springframework.boot"

	[libraries.commons-lang3]
		name = "commons-lang3"
		group = "org.apache.commons"
